### ISSUE TITLE
Error with S3Connector when credentials are missing

### ISSUE THREAD

**Issue by yurii-kazmiruk-promova** [testomatio/pytestomatio#19]
### An error occurs with S3Connector when credentials are missing.

Command `pytest --testomatio report`

Error https://d.pr/i/ZJfIJB
Code https://d.pr/i/nt6uI1

**Comment by tikolakin** [comment]
fix is available in https://github.com/testomatio/pytestomatio/releases/tag/2.8.2.dev44

**Comment by tikolakin** [comment]
fix available in 2.10.0
