### ISSUE TITLE
Test results are not being added to the test run when using parameterized browser configurations in Playwright

### ISSUE THREAD

**Issue by yurii-kazmiruk-promova** [testomatio/pytestomatio#21]
When using parameterized browser configurations in Playwright, test results are not being added to the test run in the Testomat.
The issue may be caused by square brackets ([]) in the test names generated for parameterized configurations.
https://d.pr/i/CbhTSy

fixtures:
https://d.pr/i/qT472D 
https://d.pr/i/PMAvcv 

AR: https://d.pr/i/zWyKLd

ER: https://d.pr/i/FRnWQM

**Comment by tikolakin** [comment]
Hi @yurii-kazmiruk-promova 
Could you please test it on your end - https://pypi.org/project/pytestomatio/2.8.2.dev44/ ?

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/7cf94a62-8b67-4fbc-b25a-ff4a99d688af" />
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/913fbde2-8c65-4ffb-bef6-ca182d968884" />
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/0179c759-1696-4eca-8cb4-708230407e9e" />

Please let me know how it went

**Comment by tikolakin** [comment]
fix available in 2.10.0
@yurii-kazmiruk-promova  please reopen if any issues
Thanks
